### ISSUE TITLE
allow passing merge_language to mandrill

### ISSUE THREAD

**Issue by dholdren** [wombat/mandrill_integration#5]
I'd like to use the "handlebars" merge language in some of my mandrill templates, and they allow you to do this via the API by passing a "merge_language" value:

https://mandrillapp.com/api/docs/messages.JSON.html

```json
"merge_language": "mailchimp"
```
or
```json
"merge_language": "handlebars"
```

**Comment by phstc** [comment]
hm good idea. I replied you on ZD with more details. Thanks
